export default data = [
    {
        id: 0,
        user: "sophiavieceli",
        name: "Sophia",
        email: "sophiavieceli@gmail.com",
        senha: "blablabla",
    },
    {
        id: 1,
        user: "fulano1",
        name: "Fulano",
        email: "fulano1@gmail.com",
        senha: "blablabla",
    },
    {
        id: 2,
        user: "fulano2",
        name: "Fulano",
        email: "fulano2@gmail.com",
        senha: "blablabla",
    },
    {
        id: 3,
        user: "fulano3",
        name: "Fulano",
        email: "fulano3@gmail.com",
        senha: "blablabla",
    },
    {
        id: 4,
        user: "fulano4",
        name: "Fulano",
        email: "fulano4@gmail.com",
        senha: "blablabla",
    },
    {
        id: 5,
        user: "fulano5",
        name: "fulano5",
        email: "fulano5@gmail.com",
        senha: "blablabla",
    },
    {
        id: 6,
        user: "fulano6",
        name: "Fulano",
        email: "fulano6@gmail.com",
        senha: "blablabla",
    },
    {
        id: 7,
        user: "fulano7",
        name: "Fulano",
        email: "fulano7@gmail.com",
        senha: "blablabla",
    },
];
